version: '3.7'

services:
  api:
    image: cosmicforge/blockchain-api:latest
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - CHANNEL_NAME=cosmicforge
      - CHAINCODE_NAME=patient-records
      - ORG_MSPID=Org1MSP
      - ADMIN_ID=admin
      - ADMIN_PASSWORD=adminpw
      - JWT_SECRET=${JWT_SECRET:-cosmicforge-secret}
      - CONNECTION_PROFILE_PATH=/app/connection-profile.json
      - WALLET_PATH=/app/wallet
      - LOG_LEVEL=info
      - CORS_ORIGIN=*
    volumes:
      - ./wallet:/app/wallet
      - ./connection-profile.json:/app/connection-profile.json
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Persistent volume for wallet and logs
  volumes:
    wallet_data:
    logs_data:
